#
# This is a Flox environment manifest.
# Visit flox.dev/docs/concepts/manifest/
# or see flox-edit(1), manifest.toml(5) for more information.
#
version = 1

# List packages you wish to install in your environment inside
# the `[install]` section.
[install]
_1password.pkg-path = "_1password"
_1password.version = "1password-cli-2.29.0"
awscli2.pkg-path = "awscli2"
awscli2.version = "2.17.0"
github-cli.pkg-path = "github-cli"
github-cli.version = "gh-2.52.0"
gum.pkg-path = "gum"
gum.version = "0.14.1"
# hello.pkg-path = "hello"
# nodejs = { version = "^18.4.2", pkg-path = "nodejs_18" }

# Set environment variables in the `[vars]` section. These variables may not
# reference one another, and are added to the environment without first
# expanding them. They are available for use in the `[profile]` and `[hook]`
# scripts.
[vars]
# message = "Howdy"

# The `hook.on-activate` script is run by the *bash* shell immediately upon
# activating an environment, and will not be invoked if Flox detects that the
# environment has previously been activated. Variables set by the script will
# be inherited by `[profile]` scripts defined below. Note that any stdout
# generated by the script will be redirected to stderr.
[hook]
on-activate = '''
# Function to authenticate with 1Password; this is called by the 'aws' alias in [profile]
authenticate_1password() {
    local config_file="$HOME/.config/flox/1password.session"

    [[ -f "$config_file" ]] && source "$config_file"

    if [[ "${ENABLE_1PASSWORD_PERSISTENCE}" != "true" ]]; then
        echo "1Password session persistence is not enabled. Skipping authentication."
        return 0
    fi

    # Check if the token exists and is valid
    if [[ -n "${OP_SESSION_TOKEN}" ]]; then
        if op whoami --session "${OP_SESSION_TOKEN}" >/dev/null 2>&1; then
            echo "Existing 1Password session is valid."
            return 0
        else
            echo "Existing 1Password session is invalid. Re-authenticating..."
            unset OP_SESSION_TOKEN
        fi
    else
        echo "No existing 1Password session found. Authenticating..."
    fi

    max_retries=5
    retry_count=0
    while true; do
        OP_SESSION_TOKEN=$(op signin --raw 2>&1)
        if [[ $? -eq 0 ]]; then
            # Remove the old session token and insert the new one in its place
            sed -i '/# BEGIN 1PASSWORD SESSION TOKEN/,/# END 1PASSWORD SESSION TOKEN/c\
# BEGIN 1PASSWORD SESSION TOKEN\
OP_SESSION_TOKEN='"${OP_SESSION_TOKEN}"'\
# END 1PASSWORD SESSION TOKEN' "$config_file"

            # If the session token section doesn't exist, append it
            if ! grep -q "# BEGIN 1PASSWORD SESSION TOKEN" "$config_file"; then
                echo >> "$config_file"
                echo "# BEGIN 1PASSWORD SESSION TOKEN" >> "$config_file"
                echo "OP_SESSION_TOKEN=${OP_SESSION_TOKEN}" >> "$config_file"
                echo "# END 1PASSWORD SESSION TOKEN" >> "$config_file"
            fi
            
            echo "Authentication successful."
            break
        else
            retry_count=$((retry_count + 1))
            if [[ ${retry_count} -ge ${max_retries} ]]; then
                echo "Maximum number of retries exceeded. Please check your 1Password credentials and try again."
                return 1
            else
                echo "Invalid password. Please try again."
            fi
        fi
    done

    # Here we export the OP_SESSION_TOKEN for use in the current session
    export OP_SESSION_TOKEN
}

# Call the 1Password authentication function
authenticate_1password

# Export the OP_SESSION_TOKEN for use in the profile scripts
export OP_SESSION_TOKEN

'''

# Scripts defined in the `[profile]` section are *sourced* by *your shell* and
# inherit environment variables set in the `[vars]` section and by `[hook]` scripts.
# The `profile.common` script is sourced by all shells and special care should be
# taken to ensure compatibility with all shells, after which exactly one of
# `profile.{bash,fish,tcsh,zsh}` is sourced by the corresponding shell.
[profile]
common = '''
# Source the 1password.session file
[[ -f ~/.config/flox/1password.session ]] && source ~/.config/flox/1password.session

# Alias to run the aws command. Set the OP_VAULT, OP_AWS_CREDENTIALS, and
# OP_AWS_USERNAME_FIELD variables in ~/.config/flox/1password.session.
# Alternatively, you can hard-code your credentials in the command below
# or as environment variables in the [vars] section above!
alias aws='op run --session "${OP_SESSION_TOKEN}" --env-file <(printf "%s\n" AWS_ACCESS_KEY_ID=op://${OP_VAULT}/${OP_AWS_CREDENTIALS}/${OP_AWS_USERNAME_FIELD} AWS_SECRET_ACCESS_KEY=op://${OP_VAULT}/${OP_AWS_CREDENTIALS}/${OP_AWS_CREDENTIALS_FIELD}) -- aws'alias aws='op run --session "${OP_SESSION_TOKEN}" --env-file <(printf "%s\n" AWS_ACCESS_KEY_ID=op://${OP_VAULT}/${OP_AWS_CREDENTIALS}/username AWS_SECRET_ACCESS_KEY=op://${OP_VAULT}/${OP_AWS_CREDENTIALS}/credential) -- aws'
'''

# Additional options can be set in the `[options]` section. Refer to
# manifest.toml(5) for a list of available options.
[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]


